### ISSUE TITLE
move to Connectors_Molex.pretty

### ISSUE THREAD

**Issue by pointhi** [KiCad/Sockets_MOLEX_KK-System.pretty#1]
From what I see we could simply move this library to https://github.com/KiCad/Connectors_Molex.pretty.

Because the footprints have no specific informations, this PR could represent the same footprint: https://github.com/KiCad/Connectors_Molex.pretty/pull/8

@CarlPoirier, @ricardocrudo what do you think?

**Comment by evanshultz** [comment]
@pointhi @SchrodingersGat @poeschlr @jkriege2 
I believe this Issue can be closed as these appear to have been moved and updated already as KK 6410 footprints in the library mentioned above. Right?

**Comment by SchrodingersGat** [comment]
I believe you are correct - this lib should be marked as deprecated and removed from fp-lib

**Comment by poeschlr** [comment]
@SchrodingersGat this lib is sill in the list of libs i can add via the library wizard if i select github as source.

**Comment by SchrodingersGat** [comment]
@poeschlr thanks - I'll submit a PR removing this lib from the table

**Comment by evanshultz** [comment]
Closing since this was already resolved.
